WIP: Angular10
AnSyn/ansyn pull request #3360
Opened 2020-08-05 14:43 UTC by tltk90

2020-09-14 10:18 UTC, sulimani55 requested changes

2020-09-17 12:02 UTC, tltk90 commented on resources/ansyn-lint-settings.xml
>      <indentOptions>
is our lint for webstrom.
each one from our team should use this lint.
to prevent difference in lint from one PR to another.

2020-09-17 13:11 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/overlays.app.effects.ts
> +					const id = (displayOverlayHistory[mapId] || []).slice(-1)[0]; // get last overlay id from history
pop remove the element from the array,
and displayOverlayHistory come from the store and therefore it is immutable

2020-09-23 12:51 UTC, ramtob commented on src/app/@ansyn/ansyn/ansyn/ansyn.component.ts
> +		return true;
@sulimani55 
My guess is that if we don't return true, the event (window closing) will be cancelled, that is the window will not close. We have a similar behavior with other events, such as onSubmit.

2020-09-23 12:55 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/alerts/components/alerts-container/alerts-container.component.ts
> +			return false;
@sulimani55 
Yes, it's possible. Unless for some reason we distinguish between `false` and `undefined`...

2020-09-23 12:57 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/core/utils/rxjs/operators/rxPreventCrash.ts
>  	});
@sulimani55 
Good question, I don't know

2020-09-23 13:01 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/help/components/help.component.less
> +@ansyn-help-slide-height: calc(~"100vh - (@{ansyn-help-footer-height} * 2)");
@sulimani55 
I don't remember. And the help component seems to have been removed now. Maybe it now a change in visual design?

2020-09-23 13:07 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/help/help.module.ts
> +export function helpAppInitializeFactory(store: Store<IMenuState>, menuConfig: IMenuConfig, helpStorage: HelpLocalStorageService) {
@sulimani55 
Save as above :( I don't remember this. And the help component seems to have been removed now.

2020-09-23 13:07 UTC, sulimani55 commented on src/app/@ansyn/ansyn/modules/menu-items/help/components/help.component.less
> +@ansyn-help-slide-height: calc(~"100vh - (@{ansyn-help-footer-height} * 2)");
maybe so, but its removed either way so i dont think its necessary

2020-09-23 13:08 UTC, sulimani55 commented on src/app/@ansyn/ansyn/modules/menu-items/help/help.module.ts
> +export function helpAppInitializeFactory(store: Store<IMenuState>, menuConfig: IMenuConfig, helpStorage: HelpLocalStorageService) {
trueee

2020-09-23 13:12 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/tools/components/annotations-control/annotations-control.component.ts
> +	get Boolean() {
@sulimani55 
My guess is that the purpose is to make the Boolean interface available in the HTML file. 
It seems to be not used now.

2020-09-23 13:18 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/overlays/services/overlays.service.spec.ts
> +// import { Response, ResponseOptions, XHRBackend } from '@angular/http';
@sulimani55 
I guess not

2020-09-23 13:20 UTC, ramtob commented on __ngcc_entry_points__.json
> +{"ngccVersion":"9.1.0","configFileHash":"87c535c3ce0eac2a54c246892e0e21a1","lockFileHash":"d4ebe8f48dbfd386920a4ce0e3018c3e","entryPointPaths":[]}
@sulimani55 
I don't know what is this file. It does not seem ours. Maybe Angular added it.

2020-09-23 13:22 UTC, sulimani55 commented on src/app/@ansyn/ansyn/modules/alerts/components/alerts-container/alerts-container.component.ts
> +			return false;
ok

2020-09-23 13:22 UTC, sulimani55 commented on src/app/@ansyn/ansyn/ansyn/ansyn.component.ts
> +		return true;
makes sense. thanks

2020-09-29 06:28 UTC, sulimani55 approved these changes

2020-10-11 08:25 UTC, merged