Annotations metadata template
AnSyn/ansyn pull request #3386
Opened 2020-08-27 15:41 UTC by darknath10

2020-08-30 10:55 UTC, Suzizaher commented on src/app/@ansyn/ol/plugins/annotations/annotations-context-menu/components/dynamic-metadata-form/dynamic-metadata-form.component.less
> +.inputs-container {
place classes in their ancestor class. In general try to keep classes in nested form

2020-08-31 12:04 UTC, asafMasa requested changes

2020-08-31 12:34 UTC, darknath10 commented on src/app/@ansyn/ol/plugins/annotations/annotations-context-menu/components/multi-choice-attribute/multi-choice-attribute.component.ts
> +		this.filteredOptions$ = this.addTagCtrl.valueChanges.pipe(
subscription is handled in the template with the async pipe

2020-08-31 13:15 UTC, Suzizaher approved these changes

2020-08-31 13:46 UTC, asafMasa approved these changes

2020-08-31 13:47 UTC, merged