screen view search
AnSyn/ansyn pull request #3427
Opened 2020-10-12 09:09 UTC by PiniAmiram

2020-10-12 13:34 UTC, sulimani55 approved these changes

2020-10-12 13:34 UTC, sulimani55 commented on src/app/@ansyn/ansyn/modules/core/components/context-menu/context-menu.component.ts
> +		map((geoFilter: IGeoFilterStatus) => geoFilter.type === 'ScreenView')
use CaseGeoFilters.ScreenViews

2020-10-12 13:34 UTC, sulimani55 commented on src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
> +		filter(([position, geoFilterStatus]: [IImageryMapPosition, IGeoFilterStatus]) => Boolean(position) && geoFilterStatus.type === 'ScreenView'),
use CaseGeoFilter.ScreenView

2020-10-12 13:34 UTC, sulimani55 commented on src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/visualizers/region/region.visualizer.ts
> +		if (regionAsVisualizer && !isActive && !isMinimalistViewMode && geoFilterType !== 'ScreenView') {
use CaseGeoFilter.ScreenView

2020-10-14 08:13 UTC, asafMasa requested changes

2020-10-14 08:13 UTC, asafMasa commented on src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
> +				if (zoom < VIEW_SEARCH_ZOOM_LIMIT) {
won't work on overlays
you can't use zoom on images only resolution - try to use the scale - or calculate BBOX width size in meters

2020-10-14 08:13 UTC, asafMasa commented on src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
> +const VIEW_SEARCH_DEBOUNCE_TIME = 1000;
config for meters

2020-10-18 09:16 UTC, Danaorlov1005 approved these changes

2020-10-18 14:23 UTC, tltk90 requested changes

2020-10-18 14:23 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/status-bar.app.effects.ts
> +		withLatestFrom(this.store.select(selectGeoFilterStatus)),
it should be taken from the region.
to see why,
1. draw a polygon search.
2. check the point search
3. click on the menu.

the polygon search redraw on the map, but in the geoFilter will be write `Point`

2020-10-18 14:23 UTC, tltk90 commented on src/app/@ansyn/ansyn/modules/core/components/context-menu/context-menu.component.less
> +					&:hover {
on disable make the button always gray not only on hover.

2020-10-18 14:23 UTC, tltk90 commented on src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/visualizers/region/screen-view.visualiser.ts
> +import { Actions } from '@ngrx/effects';
why screen-view need visualiser?

2020-10-18 14:23 UTC, tltk90 commented on src/app/@ansyn/imagery/utils/geo.ts
> +	const equal = difference(firstPolygon, secondPolygon) === null && difference(secondPolygon, firstPolygon) === null;
you can use booleanEqual from turf.

2020-10-22 08:16 UTC, tltk90 requested changes
💯

2020-10-22 08:16 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.ts
> +			region = {
use turf `feature` function to create a feature.

2020-10-22 08:16 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.spec.ts
> +			e: new UpdateGeoFilterStatus({active: false, type: region.geometry.type}),
region.properites.searchMode

2020-10-22 08:16 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
> +	createRegion(polygon) {
use turf `feature` instead.

2020-10-22 08:16 UTC, tltk90 commented on src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/visualizers/region/pin-point.visualizer.ts
> +		const region: Feature<Point> = {
use turf `feature` instead

2020-10-22 10:57 UTC, tltk90 approved these changes
👍

2020-10-22 10:58 UTC, merged