results table now opens through the timeline
AnSyn/ansyn pull request #3466
Opened 2020-11-01 13:36 UTC by sulimani55

2020-11-02 09:55 UTC, tltk90 requested changes
in general i think all the thing according to result-table should be inside the
`result-table` component.

2020-11-02 09:55 UTC, tltk90 commented on src/app/@ansyn/ansyn/ansyn/ansyn.component.html
> +		<button [class.active]="toggleResults" class="results-table" (click)="toggleResultsTable()">
it is not better to enter this button inside the result-table component?

2020-11-02 09:55 UTC, tltk90 commented on src/app/@ansyn/ansyn/ansyn/ansyn.component.less
> +	.results {
same as above

2020-12-08 13:36 UTC, ramtob requested changes
Nice work

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/results/components/results-table/results-table.component.less
> -	&.rtl {
RTL code missing? Please add it.

**Please check the new design in both LTR and RTL modes** 
(they are switched according to "direction" field in translations in config)

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/results/components/results/results.component.less
> +	button {
This definition should not be here. There is no `button` in the HTML

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/menu-items/results/components/results/results.component.ts
> +			resultsTableElement.setAttribute('style', `z-index: 5`);
Why do you change `z-index` on expand?

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/overlays/components/overlay-overview/overlay-overview.component.ts
> +			this.left = left - (customElement ? 275 : 150);
Why this change?
Please don't use explicit numbers, but calculations, as in master branch.

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/status-bar/components/search-panel/search-panel.component.html
> +<ansyn-time-picker-container [openTop]="false"></ansyn-time-picker-container>
👍

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ansyn/modules/status-bar/components/timepicker-presets/timepicker-presets.component.less
> +		margin-bottom: 9px !important;
Please don't use `important` (considered bad practice)

2020-12-08 13:36 UTC, ramtob commented on src/app/@ansyn/ol/plugins/annotations/annotations-context-menu/components/annotation-context-menu/annotation-context-menu.component.ts
> +
👍

2020-12-09 12:48 UTC, ramtob approved these changes
👍

2020-12-09 14:10 UTC, tltk90 approved these changes

2020-12-09 14:10 UTC, merged