open items from menu
AnSyn/ansyn pull request #3547
Opened 2021-01-07 14:01 UTC by PiniAmiram

2021-01-07 16:01 UTC, sulimani55 requested changes

2021-01-10 12:34 UTC, Danaorlov1005 commented on src/app/@ansyn/menu/menu/menu.component.html
> +	<!-- <div class="menu" #menu [class.expanded]="expand">
stays untill we decide to remove menu concept

2021-01-10 12:36 UTC, Danaorlov1005 approved these changes

2021-01-10 14:13 UTC, sulimani55 approved these changes

2021-01-10 14:23 UTC, merged