Fix back to extent at max zoom in
AnSyn/ansyn pull request #3587
Opened 2021-01-27 07:37 UTC by sulimani55

2021-01-27 12:25 UTC, RomCo13 approved these changes

2021-01-28 07:32 UTC, tltk90 reviewed
why we need use another package `turf` intersect is not enough?

2021-01-28 08:06 UTC, sulimani55 commented
> why we need use another package `turf` intersect is not enough?

@tltk90 the 'intersect' function from turf does not work for some reason when you zoom in too close.
for example: if i check the intersection between the footprint and the current extent (on a high zoom level), i will get null.
the alternative is to use another function the handles close zooms better

2021-01-28 08:25 UTC, tltk90 commented
It is weird!
that's means that there is a bug in the 'intersect' lawn function,
Or maybe the problem is with our code, in the way we use the 'intersect' function.

2021-01-28 08:27 UTC, sulimani55 commented
> It is weird!
> that's means that there is a bug in the turf 'intersect' function,
> Or maybe the problem is with our code, in the way we use the 'intersect' function.

the way we use turf's intersect is perfectly fine, we pass 2 valid polygons and for some reason it cant handle it
i guess if the extent is too small it fails. this is probably on their side.

i even tested the polygons on the geojson.io website and they're seems fine

2021-01-28 12:17 UTC, tltk90 requested changes

2021-01-28 12:17 UTC, tltk90 commented on src/app/@ansyn/imagery/utils/geo.ts
> +			const intersections = extentPolygons.features.map(feature => intersect(feature.geometry, tempPoly));
you can pass the feature itself instead of is geometry.

2021-01-28 12:17 UTC, tltk90 commented on src/app/@ansyn/imagery/utils/geo.ts
> +	return union(features[0], features[1]);
revert.
union can get more than two features.

2021-01-28 12:32 UTC, tltk90 approved these changes

2021-01-28 14:15 UTC, Danaorlov1005 approved these changes

2021-01-28 14:32 UTC, merged