dont auto search when in screen view
AnSyn/ansyn pull request #3600
Opened 2021-01-31 16:39 UTC by tltk90

2021-02-01 10:14 UTC, tltk90 commented on src/app/@ansyn/ansyn/app-effects/effects/status-bar.app.effects.ts
> +				options.noInitialSearch = true;
for not make search the `searchByExtentPolygon` effect will take care of it,
in case of `screenView` filter.

2021-02-01 10:15 UTC, tltk90 commented on src/app/@ansyn/ansyn/modules/core/services/http-request-cache/cache-interceptors.service.ts
> +		return cachedResponse ? of(cachedResponse).pipe(delay(200)) : this.requestHandler(req, next);
Yes. Although it is not necessary according to the Aviv.

2021-02-01 10:16 UTC, Danaorlov1005 commented on src/app/@ansyn/ansyn/modules/core/services/http-request-cache/cache-interceptors.service.ts
> +		return cachedResponse ? of(cachedResponse).pipe(delay(200)) : this.requestHandler(req, next);
then remove :) 
 no need to lie 😈

2021-02-01 10:18 UTC, Danaorlov1005 approved these changes

2021-02-02 08:02 UTC, sulimani55 requested changes

2021-02-02 08:02 UTC, sulimani55 commented on src/app/@ansyn/ansyn/app-effects/effects/status-bar.app.effects.ts
> +	GoAdjacentOverlay, SearchAction,
remove ,

2021-02-02 08:02 UTC, sulimani55 commented on src/app/@ansyn/ansyn/app-effects/effects/status-bar.app.effects.ts
> +				options.noInitialSearch = true;
is the 'noInitialSearch ' option still relevant? i think the initial-search problem was fixed a while ago

2021-02-02 09:06 UTC, RomCo13 approved these changes

2021-02-02 09:06 UTC, sulimani55 approved these changes

2021-02-02 09:06 UTC, merged